theme: jekyll-theme-time-machine
title: zupan
description: let's create a community owned TikTok clone
idea:
  question: Like the idea ?
  link: https://docs.google.com/forms/d/e/1FAIpQLSdl9T6qbPy235baKsr5cOzOgoDBO-WXidjZznmMHj83rLLPOGg/viewform
  title: Fill the form !
